"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const buzzController_1 = require("../controllers/buzzController");
const auth_1 = require("../middleware/auth");
const router = express_1.default.Router();
router.get('/', buzzController_1.getAllPosts);
router.get('/hashtags/trending', buzzController_1.getTrendingHashtags);
router.get('/hashtag/:hashtag', buzzController_1.getPostsByHashtag);
router.get('/:id', buzzController_1.getPostById);
router.get('/:id/comments', buzzController_1.getCommentsByPostId);
router.post('/', auth_1.authenticate, buzzController_1.createPost);
router.post('/:id/like', auth_1.authenticate, buzzController_1.likePost);
router.post('/:id/view', buzzController_1.incrementViews);
router.post('/:id/comment', auth_1.authenticate, buzzController_1.addComment);
router.post('/:id/share', auth_1.authenticate, buzzController_1.addShare);
exports.default = router;
